### PR TITLE
Added Credit Card Generator Plugin

### PR DESCRIPTION
**Pull request by guilhermearaujo**
This is a plugin to generate valid credit card numbers.

### CODE REVIEW

**Comment by marcbachmann** [comment]
lol. do you need such a plugin so often?
doesn't most payment acquirers or solution providers provide test numbers?
sorry, but the title looks hilarious.

**Comment by guilhermearaujo** [comment]
They probably do provide, but how long will you take to go to their website, find the numbers, select and copy, when you could simple type "visa" and have it in your clipboard?

**Comment by nate-parrott** [comment]
nice!
This probably won't be that useful to me but it looks really good.

**Comment by nate-parrott** [comment]
Here it is: http://flashlight.nateparrott.com/plugin/ccgenerator

**Pull request merged**
