### PR TITLE
Refactor lorem ipsum plugin

### PR DESCRIPTION
**Pull request by marcbachmann**
- Use offline lorem ipsum library
- Add dark mode support
- Add default commands & short names. e.g. lipsum 1w, lipsum 1p, lipsum 1s as short forms for 1 word, 1 sentence...
- Improve the html a bit

### CODE REVIEW

**Comment by xremix** [comment]
@marcbachmann, I also improved the lipsum plugin including a dark mode with #263.
That will run into conflict when merging, I think.

**Comment by marcbachmann** [comment]
Yes, sorry, I've seen that too late. I should have pushed my changes earlier.
Your changes in the plugin.py file aren't needed. So you can reset your last commit.

**Comment by xremix** [comment]
Ok, I just removed the code again.

**Comment by nate-parrott** [comment]
I'm just gonna pull and merge them as best I can...

**Comment by nate-parrott** [comment]
I'm sorry, I can't get git to merge this at all. It keeps parading me through a bunch of rebases and then failing to actually merge. (actually, I have no idea what it's doing — I'm terrible at git). I'm going to close this — hopefully the changes were merged in some acceptable way. :cry:

**Comment by xremix** [comment]
@nate-parrott Sorry, I think this is my fault. Is it only the plugin.py file from the lipsum plugin? Then you can ignore my changes and just use the file (and overwrite it) from @marcbachmann .

I had no access to my computer, so I just modified the changes in the web editor from github.

**Comment by nate-parrott** [comment]
no worries! my fault for not being good at git. I *think* I successfully
managed to pull in all your changes — feel free to re-submit them if not.

**Comment by marcbachmann** [comment]
No problem. It looks like you merged everything. For next time, you don't have to rebase at all, doing a `git merge` should mostly work. You can get a conflict, but in that case it was only three lines.

Next time I can also rebase my branch so you can simply merge in the github interface. IMO you shouldn't merge the pull-requests from other developers if they contain conflicts. The developers should fix them.

**Pull request closed without merging**
