### PR TITLE
remindme.bundle - new keyword "r"

### PR DESCRIPTION
**Pull request by rbuc**
This adds a very short keyword "r" to the remindme-plugin additionally to "remind", "remind
me", etc. to very quickly enter new reminders. Analogous to "g" in the
google plugin.

### CODE REVIEW

**Comment by rbuc** [comment]
This is my very first pull-request ever, so I hope I did correctly. It's a very small change.

**Comment by marcbachmann** [comment]
@rbuc Everything's correct concerning the pull-request.

@nate-parrott what's your opinion on using such short keywords?
I haven't looked yet into your keyword parser, but I experienced some keyword mismatches in earlier versions of flashlight. I don't know whether this is fixed already.

Also a testing setup for queries would be nice.
e.g. Like I did in my modules (log to stdout) except that it should be automated.

**Comment by rbuc** [comment]
I noticed that eg. the Leo.org-plugin has a "Settings" button. Maybe having a button to allow the users to select/deselect keywords would be a good feature (parsing examples.txt into a list with checkboxes would be enough)?

**Comment by nate-parrott** [comment]
@marcbachmann in my experience, most plugin mismatches aren't caused by keyword conflicts. They're caused by parser issues or bad examples.txt files. But it probably _will_ become a problem eventually. It'd be nice to be able to assign arbitrary shortcuts to plugins — in the meantime, this is a useful patch.

**Pull request merged**
