### PR TITLE
Sublime directory search & aliases

### PR DESCRIPTION
**Pull request by marcbachmann**
screen shot 2015-01-20 at 00 06 24

- Allow shortcuts to open directories/files
- Add file search using mdfind

I'll make a few commits with those features later this or next week.
I already have some basic features.

### CODE REVIEW

**Comment by nate-parrott** [comment]
sweet! let me know when you're ready to merge.

I'm probably understanding this wrong, but what's the use of searching files with mdfind? that's what Spotlight was originally made for... 😕

**Comment by marcbachmann** [comment]
Is there a possibility to reuse the search for a plugin?
I'd like to search for a directory and open it in sublime.

**Comment by nate-parrott** [comment]
Ahh, I see
Not possible with the current API (although it could be done)

**Comment by marcbachmann** [comment]
@nate-parrott this is ready.
It's much better than the current version.
But there's still enough to improve.

**Comment by nate-parrott** [comment]
this is amazing.

**Pull request merged**
