### PR TITLE
Post as Slack User, Cache File, New Settings

### LINKED ISSUE #301: Better Slack Integration
I should have some time tomorrow to fix this. But I was excited to use the Slack integration only to find that it posted as `username (bot)`. This is because the plugin is using the Incoming Webhooks API. If it used the Slack Web API and asked for a user API Token in the Plugin Settings, and used the `im.open` and `im.close` API calls. It would be more useful. Right now direct messages go to the receiving users Slackbot channel, rather than their actual direct message thread.

`username_subtext` might be a nice addition too, the message would say "Mike Helmick via Flashlight", the subtext should be an optional setting, in my opinion.

### PR DESCRIPTION
**Pull request by michaelhelmick**
Fixes #301 

- Slack now posts as the user, rather than sending the message as a
BOT. They just updated their API to accept `as_user`

- There is now a cache file for channels and people to send messages
to. If you get new channels or a new team member, run `slack cache
clear` via Spotlight. Next time you send a message, the file will be
regenerated.

- New settings: Display Notification (whether to display success
notifications or not). Token (Your api token from
https://api.slack.com/web)

### CODE REVIEW

**Comment by michaelhelmick** [comment]
I'm not sure if I'm supposed to generate a new version or if that's something you guys do. Hope you like this!

**Comment by michaelhelmick** [comment]
I borrowed slacks loading background and text and link colors and attempted to pretty it up.

Examples:

No Credentials
screenshot 2015-03-06 16 55 32

With Credentials
screenshot 2015-03-06 16 55 02

**Comment by michaelhelmick** [comment]
Hm, it appears that symbols cause strange behavior in the `~message` string (as you can see above, instead of it saying "Yo, dood" -- it says "Yo , dood"

screenshot 2015-03-09 10 38 42

If I put two symbols next to each other, they will go together. But if a letter then symbol follows; it's wonky.

There is also always a space (in plugin.py) given before `message_n` is appended.

Here is a longer message. `~message` is only "!". I'm not sure if `results` takes and uses the args wrong?
screenshot 2015-03-09 10 52 21

Maybe in the message loop over each item and if it's `A-Za-z0-9` add a space, otherwise don't add a space? Opinions @AlAdler

**Comment by nate-parrott** [comment]
This looks great — I don't have a ton of time to look into the code myself, but I'll pull it in and upload it. Sorry for the delay!

**Comment by AlAdler** [comment]
Sorry for the delayed response. Looks great!

**Pull request merged**
